language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mongodb

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - DB=mongodb

matrix:
  allow_failures:
    - php: hhvm

install: composer install --no-interaction

before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
