language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mongodb

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - DB=mongodb

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != '7.0' ]; then pecl install mongodb; fi
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
